/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteJarel;

/**
 *
 * @author jacks
 */
public class JFCadastroFor extends javax.swing.JFrame {

    /**
     * Creates new form JFCadastroFor
     */
    public JFCadastroFor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lbl_empresaForCad = new javax.swing.JLabel();
        lbl_picoleForCad = new javax.swing.JLabel();
        lbl_sairForCad = new javax.swing.JLabel();
        lbl_TruckIconForCad = new javax.swing.JLabel();
        lbl_sairIconForCad = new javax.swing.JLabel();
        lbl_menuForCad = new javax.swing.JLabel();
        lbl_menuIconForCad = new javax.swing.JLabel();
        lbl_FornecedorForCad = new javax.swing.JLabel();
        btn_cadastrarFor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 252, 237));
        jPanel6.setMaximumSize(new java.awt.Dimension(1010, 700));
        jPanel6.setMinimumSize(new java.awt.Dimension(1010, 700));

        lbl_empresaForCad.setFont(new java.awt.Font("Monotype Corsiva", 2, 48)); // NOI18N
        lbl_empresaForCad.setText("Jarel Sorvetes");

        lbl_picoleForCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/picole.png"))); // NOI18N

        lbl_sairForCad.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairForCad.setText("Sair");

        lbl_TruckIconForCad.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_TruckIconForCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/truck-fast_48px.png"))); // NOI18N

        lbl_sairIconForCad.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairIconForCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/exit-to-app (1).png"))); // NOI18N

        lbl_menuForCad.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuForCad.setText("Menu");

        lbl_menuIconForCad.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuIconForCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/menu.png"))); // NOI18N
        lbl_menuIconForCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuIconForCadMouseClicked(evt);
            }
        });

        lbl_FornecedorForCad.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_FornecedorForCad.setText("Cadastrar fornecedores");

        btn_cadastrarFor.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_cadastrarFor.setText("Cadastrar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_TruckIconForCad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_FornecedorForCad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_empresaForCad, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lbl_picoleForCad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lbl_menuForCad)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_menuIconForCad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lbl_sairForCad)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_sairIconForCad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cadastrarFor)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_picoleForCad)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_menuForCad)
                            .addComponent(lbl_menuIconForCad)
                            .addComponent(lbl_sairForCad)
                            .addComponent(lbl_sairIconForCad)))
                    .addComponent(lbl_empresaForCad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_TruckIconForCad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_FornecedorForCad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cadastrarFor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_menuIconForCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuIconForCadMouseClicked
        // TODO add your handling code here:
        JFMenu menu = new JFMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_menuIconForCadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastroFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastroFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastroFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastroFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastroFor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarFor;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_FornecedorForCad;
    private javax.swing.JLabel lbl_TruckIconForCad;
    private javax.swing.JLabel lbl_empresaForCad;
    private javax.swing.JLabel lbl_menuForCad;
    private javax.swing.JLabel lbl_menuIconForCad;
    private javax.swing.JLabel lbl_picoleForCad;
    private javax.swing.JLabel lbl_sairForCad;
    private javax.swing.JLabel lbl_sairIconForCad;
    // End of variables declaration//GEN-END:variables
}
