/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteJarel;

import java.sql.Connection;

/**
 *
 * @author manager
 */
public class JFCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JFCadastro
     */
    public JFCadastro() {
        initComponents();
        lbl_status.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_senhaCad = new javax.swing.JLabel();
        lbl_nomeCad = new javax.swing.JLabel();
        txt_nomeCad = new javax.swing.JTextField();
        lbl_cabecario = new javax.swing.JLabel();
        btn_voltarCad = new javax.swing.JButton();
        btn_cadastrarCad = new javax.swing.JButton();
        lbl_icon = new javax.swing.JLabel();
        lbl_confirmaCad = new javax.swing.JLabel();
        lbl_enderecoCad = new javax.swing.JLabel();
        txt_enderecoCad = new javax.swing.JTextField();
        txt_senhaCad = new javax.swing.JPasswordField();
        txt_confirmarCad = new javax.swing.JPasswordField();
        txt_cpfCad = new javax.swing.JTextField();
        lbl_cpfCad = new javax.swing.JLabel();
        lbl_emailCad = new javax.swing.JLabel();
        txt_emailCad = new javax.swing.JTextField();
        lbl_codfun = new javax.swing.JLabel();
        txt_codfunc = new javax.swing.JTextField();
        lbl_nomeCad1 = new javax.swing.JLabel();
        rad_sFemi = new javax.swing.JRadioButton();
        rad_sMasc = new javax.swing.JRadioButton();
        cbx_cidades = new javax.swing.JComboBox<>();
        lbl_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setSize(new java.awt.Dimension(580, 520));

        jPanel1.setBackground(new java.awt.Color(255, 252, 237));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(505, 561));
        jPanel1.setMinimumSize(new java.awt.Dimension(505, 561));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(505, 561));

        lbl_senhaCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_senhaCad.setText("Senha:");

        lbl_nomeCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_nomeCad.setText("Nome:");

        txt_nomeCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        txt_nomeCad.setName("txt_nome"); // NOI18N

        lbl_cabecario.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_cabecario.setText("Cadastro");

        btn_voltarCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        btn_voltarCad.setText("Voltar");
        btn_voltarCad.setName("btn_esquece"); // NOI18N
        btn_voltarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarCadActionPerformed(evt);
            }
        });

        btn_cadastrarCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        btn_cadastrarCad.setText("Cadastrar");
        btn_cadastrarCad.setName("btn_cadastrarCad"); // NOI18N
        btn_cadastrarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarCadActionPerformed(evt);
            }
        });

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/logo_icon.png"))); // NOI18N

        lbl_confirmaCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_confirmaCad.setText("Confirmar senha:");

        lbl_enderecoCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_enderecoCad.setText("Endereço:");

        txt_enderecoCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        txt_enderecoCad.setName("txt_senha"); // NOI18N

        txt_senhaCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N

        txt_confirmarCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N

        txt_cpfCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        txt_cpfCad.setName("txt_senha"); // NOI18N

        lbl_cpfCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_cpfCad.setText("CPF:");

        lbl_emailCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_emailCad.setText("E-mail:");

        txt_emailCad.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        txt_emailCad.setName("txt_senha"); // NOI18N

        lbl_codfun.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_codfun.setText("Cod do funcionario");

        txt_codfunc.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        txt_codfunc.setName("txt_senha"); // NOI18N

        lbl_nomeCad1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_nomeCad1.setText("Sexo:");

        rad_sFemi.setBackground(new java.awt.Color(255, 252, 237));
        rad_sFemi.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        rad_sFemi.setText("Feminino");

        rad_sMasc.setBackground(new java.awt.Color(255, 252, 237));
        rad_sMasc.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        rad_sMasc.setText("Masculino");

        cbx_cidades.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        cbx_cidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cidades" }));

        lbl_status.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_status.setText("cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_enderecoCad)
                                .addComponent(lbl_cpfCad)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_icon)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_nomeCad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_status)
                            .addComponent(lbl_nomeCad1)
                            .addComponent(lbl_codfun)
                            .addComponent(btn_cadastrarCad)
                            .addComponent(lbl_emailCad)
                            .addComponent(lbl_senhaCad)
                            .addComponent(lbl_confirmaCad))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_emailCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rad_sFemi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_sMasc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lbl_cabecario))
                            .addComponent(txt_cpfCad, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txt_enderecoCad)
                            .addComponent(txt_codfunc)
                            .addComponent(txt_nomeCad)
                            .addComponent(txt_senhaCad)
                            .addComponent(txt_confirmarCad)
                            .addComponent(cbx_cidades, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btn_voltarCad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_cabecario)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nomeCad)
                            .addComponent(txt_nomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_icon))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeCad1)
                    .addComponent(rad_sFemi)
                    .addComponent(rad_sMasc))
                .addGap(18, 18, 18)
                .addComponent(cbx_cidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_enderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_enderecoCad))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_emailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_emailCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_senhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_senhaCad))
                        .addGap(18, 18, 18)
                        .addComponent(txt_confirmarCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_confirmaCad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codfun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lbl_status)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarCad)
                    .addComponent(btn_voltarCad))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(474, 671));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarCadActionPerformed
        // TODO add your handling code here:
        JFLogin log = new JFLogin();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarCadActionPerformed

    private void btn_cadastrarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarCadActionPerformed
        String sexo = null, senha, cSenha, cod; 
        
        Connection conexao =  ConexaoDB.abrirConexao();        
        CadastroBean cadB = new CadastroBean();        
        CadastroDAO cadD = new CadastroDAO(conexao);
        
        senha       =   txt_senhaCad.getText();
        cSenha     = txt_confirmarCad.getText();    
        if(senha==cSenha)
        {
            cadB.setNome(txt_nomeCad.getText());
            cadB.setCpf(txt_cpfCad.getText());
            cadB.setEmail(txt_emailCad.getText());
            cadB.setCidade(cbx_cidades.getSelectedItem().toString());
            cadB.setEndereco(txt_enderecoCad.getText());
            cadB.setSenha(txt_senhaCad.getName());
            cod=txt_codfunc.getText();            
            if(rad_sFemi.isSelected())
            {
                sexo = "feminino";
            }
            else if (rad_sMasc.isSelected())
            {
                sexo = "masculino";
            }
            cadB.setSexo(sexo);
            lbl_status.setText(cadD.inserirCliente(cadB));      
            
            lbl_status.setVisible(true);
        }
    }//GEN-LAST:event_btn_cadastrarCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarCad;
    private javax.swing.JButton btn_voltarCad;
    private javax.swing.JComboBox<String> cbx_cidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cabecario;
    private javax.swing.JLabel lbl_codfun;
    private javax.swing.JLabel lbl_confirmaCad;
    private javax.swing.JLabel lbl_cpfCad;
    private javax.swing.JLabel lbl_emailCad;
    private javax.swing.JLabel lbl_enderecoCad;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_nomeCad;
    private javax.swing.JLabel lbl_nomeCad1;
    private javax.swing.JLabel lbl_senhaCad;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JRadioButton rad_sFemi;
    private javax.swing.JRadioButton rad_sMasc;
    private javax.swing.JTextField txt_codfunc;
    private javax.swing.JPasswordField txt_confirmarCad;
    private javax.swing.JTextField txt_cpfCad;
    private javax.swing.JTextField txt_emailCad;
    private javax.swing.JTextField txt_enderecoCad;
    private javax.swing.JTextField txt_nomeCad;
    private javax.swing.JPasswordField txt_senhaCad;
    // End of variables declaration//GEN-END:variables
}
