/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PacoteJarel;

/**
 *
 * @author manager
 */
public class JFFornecedores extends javax.swing.JFrame {

    /** Creates new form JFFornecedores */
    public JFFornecedores() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbl_empresaFor = new javax.swing.JLabel();
        lbl_picoleFor = new javax.swing.JLabel();
        lbl_FornecedorFor = new javax.swing.JLabel();
        lbl_sairFor = new javax.swing.JLabel();
        lbl_TruckIconFor = new javax.swing.JLabel();
        lbl_BemvindoFor = new javax.swing.JLabel();
        lbl_sairIconFor = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_For = new javax.swing.JTable();
        btn_cadastrarFor = new javax.swing.JButton();
        btn_excluirFor = new javax.swing.JButton();
        btn_editarFor = new javax.swing.JButton();
        lbl_menuFor = new javax.swing.JLabel();
        lbl_menuIconFor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 237));

        jPanel6.setBackground(new java.awt.Color(255, 252, 237));
        jPanel6.setMaximumSize(new java.awt.Dimension(1010, 700));
        jPanel6.setMinimumSize(new java.awt.Dimension(1010, 700));

        lbl_empresaFor.setFont(new java.awt.Font("Monotype Corsiva", 2, 48)); // NOI18N
        lbl_empresaFor.setText("Jarel Sorvetes");

        lbl_picoleFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/picole.png"))); // NOI18N

        lbl_FornecedorFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_FornecedorFor.setText("Fornecedores");

        lbl_sairFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairFor.setText("Sair");

        lbl_TruckIconFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_TruckIconFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/truck-fast_48px.png"))); // NOI18N

        lbl_BemvindoFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_BemvindoFor.setText("Bem vindo usuario");

        lbl_sairIconFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairIconFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/exit-to-app (1).png"))); // NOI18N

        tbl_For.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tbl_For.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Empresa", "CNPJ", "Telefone", "Endereço", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbl_For);

        btn_cadastrarFor.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_cadastrarFor.setText("Cadastrar");

        btn_excluirFor.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_excluirFor.setText("Excluir");

        btn_editarFor.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_editarFor.setText("Editar");

        lbl_menuFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuFor.setText("Menu");

        lbl_menuIconFor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuIconFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/menu.png"))); // NOI18N
        lbl_menuIconFor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuIconForMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_cadastrarFor)
                                .addGap(258, 258, 258)
                                .addComponent(btn_editarFor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_excluirFor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lbl_TruckIconFor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_FornecedorFor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_menuFor))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lbl_BemvindoFor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_empresaFor, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lbl_picoleFor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(lbl_sairFor)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_sairIconFor)
                            .addComponent(lbl_menuIconFor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lbl_BemvindoFor)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lbl_TruckIconFor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_FornecedorFor)
                                            .addComponent(lbl_menuFor)
                                            .addComponent(lbl_menuIconFor)))))
                            .addComponent(lbl_empresaFor)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lbl_sairFor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_sairIconFor)
                            .addComponent(lbl_picoleFor))
                        .addGap(100, 100, 100)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluirFor)
                    .addComponent(btn_editarFor)
                    .addComponent(btn_cadastrarFor))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_menuIconForMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuIconForMouseClicked
        // TODO add your handling code here:
        JFMenu menu = new JFMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_menuIconForMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cadastrar1;
    private javax.swing.JButton btn_cadastrar2;
    private javax.swing.JButton btn_cadastrar3;
    private javax.swing.JButton btn_cadastrarFor;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_editar1;
    private javax.swing.JButton btn_editar2;
    private javax.swing.JButton btn_editar3;
    private javax.swing.JButton btn_editarFor;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_excluir1;
    private javax.swing.JButton btn_excluir2;
    private javax.swing.JButton btn_excluir3;
    private javax.swing.JButton btn_excluirFor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lbl_Bemvindo;
    private javax.swing.JLabel lbl_Bemvindo1;
    private javax.swing.JLabel lbl_Bemvindo2;
    private javax.swing.JLabel lbl_Bemvindo3;
    private javax.swing.JLabel lbl_BemvindoFor;
    private javax.swing.JLabel lbl_Fornecedor;
    private javax.swing.JLabel lbl_Fornecedor1;
    private javax.swing.JLabel lbl_Fornecedor2;
    private javax.swing.JLabel lbl_Fornecedor3;
    private javax.swing.JLabel lbl_FornecedorFor;
    private javax.swing.JLabel lbl_TruckIcon;
    private javax.swing.JLabel lbl_TruckIcon1;
    private javax.swing.JLabel lbl_TruckIcon2;
    private javax.swing.JLabel lbl_TruckIcon3;
    private javax.swing.JLabel lbl_TruckIconFor;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_empresa1;
    private javax.swing.JLabel lbl_empresa2;
    private javax.swing.JLabel lbl_empresa3;
    private javax.swing.JLabel lbl_empresaFor;
    private javax.swing.JLabel lbl_menuFor;
    private javax.swing.JLabel lbl_menuIconFor;
    private javax.swing.JLabel lbl_picole;
    private javax.swing.JLabel lbl_picole1;
    private javax.swing.JLabel lbl_picole2;
    private javax.swing.JLabel lbl_picole3;
    private javax.swing.JLabel lbl_picoleFor;
    private javax.swing.JLabel lbl_sair;
    private javax.swing.JLabel lbl_sair1;
    private javax.swing.JLabel lbl_sair2;
    private javax.swing.JLabel lbl_sair3;
    private javax.swing.JLabel lbl_sairFor;
    private javax.swing.JLabel lbl_sairIcon;
    private javax.swing.JLabel lbl_sairIcon1;
    private javax.swing.JLabel lbl_sairIcon2;
    private javax.swing.JLabel lbl_sairIcon3;
    private javax.swing.JLabel lbl_sairIconFor;
    private javax.swing.JTable tbl_For;
    // End of variables declaration//GEN-END:variables

}
