/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteJarel;

/**
 *
 * @author manager
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        lbl_mensagem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_senhaLo = new javax.swing.JLabel();
        lbl_nomeLo1 = new javax.swing.JLabel();
        txt_nomeLo = new javax.swing.JTextField();
        txt_senhaLo = new javax.swing.JTextField();
        lbl_login = new javax.swing.JLabel();
        btn_entrarLo = new javax.swing.JButton();
        btn_cadastrarLo = new javax.swing.JButton();
        btn_entrarLo1 = new javax.swing.JButton();
        lbl_mensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setName("JFLogin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 510));

        jPanel1.setBackground(new java.awt.Color(255, 252, 237));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(850, 510));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 510));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/logo.png"))); // NOI18N

        lbl_senhaLo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_senhaLo.setText("Senha:");

        lbl_nomeLo1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_nomeLo1.setText("Nome:");

        txt_nomeLo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txt_nomeLo.setName("txt_nome"); // NOI18N

        txt_senhaLo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txt_senhaLo.setName("txt_senha"); // NOI18N

        lbl_login.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lbl_login.setText("Login");

        btn_entrarLo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_entrarLo.setText("Esqueceu a senha?");
        btn_entrarLo.setName("btn_esquece"); // NOI18N
        btn_entrarLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarLoActionPerformed(evt);
            }
        });

        btn_cadastrarLo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_cadastrarLo.setText("Cadastrar");
        btn_cadastrarLo.setName("btn_cadastrar"); // NOI18N
        btn_cadastrarLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarLoActionPerformed(evt);
            }
        });

        btn_entrarLo1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_entrarLo1.setText("Entrar");
        btn_entrarLo1.setName("btn_entrar"); // NOI18N
        btn_entrarLo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarLo1ActionPerformed(evt);
            }
        });

        lbl_mensagem.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_mensagem.setText("status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_logo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lbl_login)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_entrarLo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cadastrarLo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_senhaLo)
                                    .addComponent(lbl_nomeLo1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nomeLo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_senhaLo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_entrarLo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lbl_mensagem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_login)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeLo1)
                    .addComponent(txt_nomeLo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senhaLo)
                    .addComponent(txt_senhaLo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_entrarLo1)
                    .addComponent(btn_cadastrarLo))
                .addGap(18, 18, 18)
                .addComponent(btn_entrarLo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_mensagem)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarLoActionPerformed
        // TODO add your handling code here:
        lbl_mensagem.setText("Ainda não vai");
        lbl_mensagem.setVisible(true);
    }//GEN-LAST:event_btn_entrarLoActionPerformed

    private void btn_entrarLo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarLo1ActionPerformed
        JFMenu menu = new JFMenu();
        LoginBean logar= new LoginBean();        
        
        if(logar.login(txt_nomeLo.getText(), txt_senhaLo.getText())==true)
        {
            menu.setVisible(true);
            dispose();
        }
        else
        {            
            lbl_mensagem.setText("senha ou login incorretos");
            lbl_mensagem.setVisible(true);
        }   
    }//GEN-LAST:event_btn_entrarLo1ActionPerformed

    private void btn_cadastrarLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarLoActionPerformed
        JFCadastro cad = new JFCadastro();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cadastrarLoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarLo;
    private javax.swing.JButton btn_entrarLo;
    private javax.swing.JButton btn_entrarLo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_mensagem;
    private javax.swing.JLabel lbl_nomeLo1;
    private javax.swing.JLabel lbl_senhaLo;
    private javax.swing.JTextField txt_nomeLo;
    private javax.swing.JTextField txt_senhaLo;
    // End of variables declaration//GEN-END:variables
}
