/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteJarel;

/**
 *
 * @author jacks
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_empresa = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_picole = new javax.swing.JLabel();
        lbl_Fornecedor = new javax.swing.JLabel();
        lbl_sair = new javax.swing.JLabel();
        lbl_sairIcon = new javax.swing.JLabel();
        lbl_Produtos = new javax.swing.JLabel();
        lbl_Relatorio = new javax.swing.JLabel();
        lbl_Caixa = new javax.swing.JLabel();
        lbl_Pedidos = new javax.swing.JLabel();
        lbl_carIcon = new javax.swing.JLabel();
        lbl_TruckIcon = new javax.swing.JLabel();
        lbl_CashIcon = new javax.swing.JLabel();
        lbl_SorveteIcon = new javax.swing.JLabel();
        lbl_Reciboicon = new javax.swing.JLabel();
        lbl_Bemvindo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(1010, 700));
        setMinimumSize(new java.awt.Dimension(1010, 700));
        setPreferredSize(new java.awt.Dimension(1010, 700));
        setSize(new java.awt.Dimension(1010, 700));

        jPanel1.setBackground(new java.awt.Color(255, 252, 237));
        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(983, 638));

        lbl_empresa.setFont(new java.awt.Font("Monotype Corsiva", 2, 48)); // NOI18N
        lbl_empresa.setText("Jarel Sorvetes");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/logoPequeno.png"))); // NOI18N

        lbl_picole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/picole.png"))); // NOI18N

        lbl_Fornecedor.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Fornecedor.setText("Fornecedores");
        lbl_Fornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_FornecedorMouseClicked(evt);
            }
        });

        lbl_sair.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sair.setText("Sair");

        lbl_sairIcon.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/exit-to-app (1).png"))); // NOI18N

        lbl_Produtos.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Produtos.setText("Produtos");

        lbl_Relatorio.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Relatorio.setText("Relatórios");

        lbl_Caixa.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Caixa.setText("Caixa");

        lbl_Pedidos.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Pedidos.setText("Pedidos/Vendas");
        lbl_Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carIconMouseClicked(evt);
            }
        });

        lbl_carIcon.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_carIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/cart_48px.png"))); // NOI18N
        lbl_carIcon.setName(""); // NOI18N
        lbl_carIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carIconMouseClicked(evt);
            }
        });

        lbl_TruckIcon.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_TruckIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/truck-fast_48px.png"))); // NOI18N
        lbl_TruckIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TruckIconMouseClicked(evt);
            }
        });

        lbl_CashIcon.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_CashIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/square-inc-cash-48px.png"))); // NOI18N

        lbl_SorveteIcon.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_SorveteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/ice-cream (1).png"))); // NOI18N

        lbl_Reciboicon.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Reciboicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/receipt.png"))); // NOI18N

        lbl_Bemvindo.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_Bemvindo.setText("Bem vindo usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_Caixa))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_TruckIcon)
                                        .addGap(173, 173, 173))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_Fornecedor)
                                        .addGap(129, 129, 129)))
                                .addComponent(lbl_CashIcon)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(lbl_SorveteIcon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(lbl_Produtos)))
                        .addGap(169, 169, 169))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbl_Bemvindo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(lbl_carIcon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_picole, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Reciboicon)
                                .addGap(30, 30, 30)))))
                .addComponent(lbl_sair)
                .addGap(15, 15, 15)
                .addComponent(lbl_sairIcon)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_Pedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Relatorio)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_sairIcon)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lbl_sair)))
                                .addGap(294, 294, 294)
                                .addComponent(lbl_Reciboicon)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Relatorio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_picole)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_empresa)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(253, 253, 253)
                                        .addComponent(lbl_carIcon)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_Pedidos))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(389, 389, 389)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_SorveteIcon)
                                            .addComponent(lbl_TruckIcon))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Fornecedor)
                                    .addComponent(lbl_Produtos)))
                            .addComponent(lbl_Bemvindo))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(lbl_CashIcon)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Caixa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_empresa.getAccessibleContext().setAccessibleName("lbl_Empresa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_TruckIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TruckIconMouseClicked
        // TODO add your handling code here:
        JFFornecedores fornece = new JFFornecedores();
        fornece.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_TruckIconMouseClicked

    private void lbl_carIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_carIconMouseClicked

    private void lbl_FornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FornecedorMouseClicked
        // TODO add your handling code here:
        JFFornecedores fornece = new JFFornecedores();
        fornece.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_FornecedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Bemvindo;
    private javax.swing.JLabel lbl_Caixa;
    private javax.swing.JLabel lbl_CashIcon;
    private javax.swing.JLabel lbl_Fornecedor;
    private javax.swing.JLabel lbl_Pedidos;
    private javax.swing.JLabel lbl_Produtos;
    private javax.swing.JLabel lbl_Reciboicon;
    private javax.swing.JLabel lbl_Relatorio;
    private javax.swing.JLabel lbl_SorveteIcon;
    private javax.swing.JLabel lbl_TruckIcon;
    private javax.swing.JLabel lbl_carIcon;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_picole;
    private javax.swing.JLabel lbl_sair;
    private javax.swing.JLabel lbl_sairIcon;
    // End of variables declaration//GEN-END:variables
}
