/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PacoteJarel;

/**
 *
 * @author manager
 */
public class JFPedido extends javax.swing.JFrame {

    /** Creates new form JFPedido */
    public JFPedido() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_usuarioPed = new javax.swing.JLabel();
        lbl_empresaPed = new javax.swing.JLabel();
        lbl_picolePed = new javax.swing.JLabel();
        lbl_menuPed = new javax.swing.JLabel();
        lbl_menuIconPed = new javax.swing.JLabel();
        lbl_sairPed = new javax.swing.JLabel();
        lbl_sairIconPed = new javax.swing.JLabel();
        lbl_carIconPed = new javax.swing.JLabel();
        lbl_pedidosPed = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produtos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 237));
        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(983, 638));

        lbl_usuarioPed.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lbl_usuarioPed.setText("Usuário X");

        lbl_empresaPed.setFont(new java.awt.Font("Monotype Corsiva", 2, 48)); // NOI18N
        lbl_empresaPed.setText("Jarel Sorvetes");

        lbl_picolePed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/picole.png"))); // NOI18N

        lbl_menuPed.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuPed.setText("Menu");
        lbl_menuPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuPedMouseClicked(evt);
            }
        });

        lbl_menuIconPed.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuIconPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/menu.png"))); // NOI18N
        lbl_menuIconPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuIconPedMouseClicked(evt);
            }
        });

        lbl_sairPed.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairPed.setText("Sair");

        lbl_sairIconPed.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairIconPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/exit-to-app (1).png"))); // NOI18N

        lbl_carIconPed.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_carIconPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/cart_48px.png"))); // NOI18N
        lbl_carIconPed.setName(""); // NOI18N
        lbl_carIconPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carIconPedMouseClicked(evt);
            }
        });

        lbl_pedidosPed.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_pedidosPed.setText("Pedidos/Vendas");
        lbl_pedidosPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pedidosPedlbl_carIconMouseClicked(evt);
            }
        });

        tbl_produtos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tbl_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Produto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_produtos);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_usuarioPed)
                                .addGap(191, 191, 191)
                                .addComponent(lbl_empresaPed, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lbl_picolePed, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_sairPed))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_carIconPed)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_pedidosPed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_menuPed)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_menuIconPed, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sairIconPed)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_sairIconPed)
                        .addComponent(lbl_picolePed)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lbl_usuarioPed))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lbl_empresaPed))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_sairPed)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_pedidosPed)
                    .addComponent(lbl_carIconPed)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_menuPed)
                        .addComponent(lbl_menuIconPed)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_menuIconPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuIconPedMouseClicked
        // TODO add your handling code here:
        JFMenu menu = new JFMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_menuIconPedMouseClicked

    private void lbl_carIconPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carIconPedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_carIconPedMouseClicked

    private void lbl_pedidosPedlbl_carIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pedidosPedlbl_carIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_pedidosPedlbl_carIconMouseClicked

    private void lbl_menuPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuPedMouseClicked
        // TODO add your handling code here:
        JFMenu menu = new JFMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_menuPedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_carIconPed;
    private javax.swing.JLabel lbl_empresaPed;
    private javax.swing.JLabel lbl_menuIconPed;
    private javax.swing.JLabel lbl_menuPed;
    private javax.swing.JLabel lbl_pedidosPed;
    private javax.swing.JLabel lbl_picolePed;
    private javax.swing.JLabel lbl_sairIconPed;
    private javax.swing.JLabel lbl_sairPed;
    private javax.swing.JLabel lbl_usuarioPed;
    private javax.swing.JTable tbl_produtos;
    // End of variables declaration//GEN-END:variables

}
