/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteJarel;

/**
 *
 * @author jacks
 */
public class JFRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form JFRelatorio
     */
    public JFRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_usuarioRe = new javax.swing.JLabel();
        lbl_empresaRe = new javax.swing.JLabel();
        lbl_picoleRe = new javax.swing.JLabel();
        lbl_menuRe = new javax.swing.JLabel();
        lbl_menuIconRe = new javax.swing.JLabel();
        lbl_sairRe = new javax.swing.JLabel();
        lbl_sairIconRe = new javax.swing.JLabel();
        lbl_reciboiconRe = new javax.swing.JLabel();
        lbl_relatorioRe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 237));
        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(983, 638));

        lbl_usuarioRe.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lbl_usuarioRe.setText("Usuário X");

        lbl_empresaRe.setFont(new java.awt.Font("Monotype Corsiva", 2, 48)); // NOI18N
        lbl_empresaRe.setText("Jarel Sorvetes");

        lbl_picoleRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/picole.png"))); // NOI18N

        lbl_menuRe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuRe.setText("Menu");
        lbl_menuRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuReMouseClicked(evt);
            }
        });

        lbl_menuIconRe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_menuIconRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/menu.png"))); // NOI18N
        lbl_menuIconRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuIconReMouseClicked(evt);
            }
        });

        lbl_sairRe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairRe.setText("Sair");

        lbl_sairIconRe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_sairIconRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/exit-to-app (1).png"))); // NOI18N

        lbl_reciboiconRe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_reciboiconRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJarel/Icons/receipt.png"))); // NOI18N

        lbl_relatorioRe.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_relatorioRe.setText("Relatórios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_usuarioRe)
                        .addGap(191, 191, 191)
                        .addComponent(lbl_empresaRe, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lbl_picoleRe, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_sairRe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_reciboiconRe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_relatorioRe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_menuRe)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_menuIconRe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sairIconRe))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_reciboiconRe)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_sairIconRe)
                                .addComponent(lbl_picoleRe)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbl_usuarioRe))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lbl_empresaRe))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lbl_sairRe)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_menuRe)
                                .addComponent(lbl_relatorioRe))
                            .addComponent(lbl_menuIconRe))))
                .addContainerGap(553, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_menuReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuReMouseClicked
        // TODO add your handling code here:
        JFMenu menu = new JFMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_menuReMouseClicked

    private void lbl_menuIconReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuIconReMouseClicked
        // TODO add your handling code here:
        JFMenu menu = new JFMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_menuIconReMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_empresaRe;
    private javax.swing.JLabel lbl_menuIconRe;
    private javax.swing.JLabel lbl_menuRe;
    private javax.swing.JLabel lbl_picoleRe;
    private javax.swing.JLabel lbl_reciboiconRe;
    private javax.swing.JLabel lbl_relatorioRe;
    private javax.swing.JLabel lbl_sairIconRe;
    private javax.swing.JLabel lbl_sairRe;
    private javax.swing.JLabel lbl_usuarioRe;
    // End of variables declaration//GEN-END:variables
}
